apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Anup-Narkhede/manifest-repo.git
    targetRevision: HEAD
    path: ./applications/cloud-native-monitoring-app
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
