apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: monitoring-app
  name: monitoring-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monitoring-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: monitoring-app
    spec:
      containers:
        - image: anupn/monitoring-app:1
          name: frontend
          ports:
            - containerPort: 5000
          resources: {}
status: {}
