apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: monitoring-app
  name: monitoring-app
spec:
  ports:
    - name: 5000-5000
      nodePort: 30001
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: monitoring-app
  type: NodePort
status:
  loadBalancer: {}
